### ISSUE TITLE
Support for Postgres `money` data type

### ISSUE THREAD

**Issue by arikkfir** [jackc/pgx-shopspring-decimal#1]
Hi,

Any objection for adding support for PostgreSQL `money` data type? (I might be able to whip up a PR for it, just wanted to confirm here first that it makes sense)

**Comment by jackc** [comment]
As I understand it, the `money` type has some limitations such as locale dependency that make it almost always better to use `numeric` or `bigint` with application defined precision. Unless I'm mistaken on that, I'd prefer not to support something that is probably the wrong thing for the user to use.
